import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getFeaturedEvents } from '../dummy-data'

export default function Home() {
  const featuredEvents = getFeaturedEvents();

  console.log(featuredEvents);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>My Homepage</h1>  

      
    </div>
  )
}
